repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
        types: [python]
      - id: ruff-format
        types: [jupyter]
        name: ruff-format-jupyter
        args: [--line-length, "80"]

  - repo: https://github.com/pycqa/pylint
    rev: v4.0.8
    hooks:
      - id: pylint

ci:
  autoupdate_branch: main
