


# Project information

[project]
name = "xplt"
description = "Plotting for Xsuite"
readme = "README.md"
keywords = ["python"]
license = {file = "LICENSE"}
authors = [
  { name = "Philipp Niedermayer (github.com/eltos)", email = "eltos@outlook.de" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Framework :: Matplotlib",
    "Programming Language :: Python :: 3",
]
dynamic = ["version"]

requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.6",
    "numpy>=1.17.0",
    "scipy>=1.2.0",
]

# PEP 771
#default-optional-dependency-keys = [
#    "recommended",
#]

[project.optional-dependencies]
minimal= []
recommended = [
    "pint>=0.24.1,!=0.25.3", # Exclude 0.25.3 due to https://github.com/hgrecco/pint/pull/2291
]
full = [
    "pint>=0.24.1,!=0.25.3", # Exclude 0.25.3 due to https://github.com/hgrecco/pint/pull/2291
    "pandas",
]


[project.urls]
homepage = "https://github.com/eltos/xplt"
documentation = "https://xsuite.github.io/xplt"
repository = "https://github.com/xsuite/xplt"


# Build tools

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "xplt.__version__"}

[tool.setuptools]
packages = ['xplt']

[tool.ci]
max-python-version = "3.14"

[dependency-groups]
examples = [
    "xsuite",
    "jupyterlab",
    "tabulate",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
    "testbook",
]
docs = [
    "myst-nb",
    "pydata-sphinx-theme",
    "sphinx",
    "sphinx-autoapi",
    "sphinx-autodoc-typehints",
    "sphinx-codeautolink",
    "sphinx-gallery",
    "sphinx-jinja2-compat",
    "sphinx-prompt",
    "sphinx-tabs",
    "sphinx-toolbox",
    "sphinxcontrib-napoleon",
]
dev = [
    "prek>=0.5.0",
]


# Dev tools

[tool.ruff]
line-length = 98
target-version = "py312"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "I",
    "UP",
]

[tool.pylint.main]
load-plugins = ["pylint.extensions.docparams"]
disable = ["all"]
enable = ["parameter_documentation"]

[tool.pylint.parameter_documentation]
default-docstring-type = "google"

[tool.pylint.basic]
no-docstring-rgx = "^(?!.*)_" # also check private and magic methods "^(?!__init__$)_"

