name: Dependencies

on:
  # Warning: this workflow must not be triggered by push or pull_request to avoid infinite loops!
  workflow_dispatch:
  schedule:
    - cron: '47 8 19 * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dependencies.yaml'
      - 'pyproject.toml'
      - 'uv.lock'

permissions:
  pull-requests: write
  # Note: DEPENDENCY_WORKFLOW_KEY is used, such that CI will be triggered on push

concurrency:
  group: ${{ github.workflow }}

env:
  PYTHON_VERSIONS: 3.11 3.12 3.13 3.14

jobs:
  update-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # force checkout branch since schedule runs on main by default
          ssh-key: ${{ secrets.DEPENDENCY_WORKFLOW_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install supported Python versions
        run: uv python install ${{ env.PYTHON_VERSIONS }}

      - name: Update dependencies
        run: |
          uv lock --upgrade

      - name: Open PR
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          commit-message: Dependency updates
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: deps/dependency-updates
          base: main
          delete-branch: true
          title: Dependency updates
          labels: |
              dependencies
          body: |
            Dependency updates. 
            See https://github.com/xsuite/xplt/wiki/maintenance for further information, guidance and troubleshooting.

