name: Release

on:
  push:
    tags:
      - v*

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install project
        run: uv sync --locked

      - name: Check versions
        run: |
          # Assert git and Python versions match
          VERSION_PY=$(uv run python -c "from xplt import __version__; print('v' + __version__)")
          echo "Python version: $VERSION_PY"
          VERSION_GIT=$(git describe --tags)
          echo "Git version tag: $VERSION_GIT"
          if [ "$VERSION_GIT" != "$VERSION_PY" ]; then
            echo "Version mismatch!"
            exit 1
          fi

  build:
    needs: checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install project
        run: uv sync --locked

      - name: Build
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: dist/

  build-docs:
    needs: checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked --group examples --group docs

      - name: Build documentation
        run: |
          uv run sphinx-build docs _build/html

      - name: Determine documentation version
        run: |
          VERSION=$(uv run python -c "from docs.conf import version; print('.'.join(version.split('.')[:2]))")
          IS_CLEAN=$(uv run python -c "from docs.conf import version; import re; print(1 if re.fullmatch(r'\d+(\.\d+(\.\d+)?)?', version) else 0)")
          
          echo "VERSION=$VERSION"
          echo "IS_CLEAN=$IS_CLEAN"
          
          {
            echo "VERSION=$VERSION"
            echo "IS_CLEAN=$IS_CLEAN"
          } > docs-metadata.env

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: _build/html/

      - name: Upload documentation metadata
        uses: actions/upload-artifact@v4
        with:
          name: documentation-metadata
          path: docs-metadata.env

  pypi-test:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist/

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

  ready:
    needs: [checks, build-docs, pypi-test]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Check release version
        run: |
          VERSION=$(git describe --tags)
          echo "Version: $VERSION"
          if [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$ ]]; then
            echo "Ready for publication"
          else
            echo "Not publishing dirty versions"
            exit 1
          fi

  docs-publish:
    needs: ready
    runs-on: ubuntu-24.04
    env:
      PAGES_BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: _build/html

      - name: Download documentation metadata
        uses: actions/download-artifact@v4
        with:
          name: documentation-metadata
          path: .

      - name: Load documentation metadata
        run: cat docs-metadata.env >> "$GITHUB_ENV"

      - name: Deploy docs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          
          git checkout "$PAGES_BRANCH"
          
          # Copy to version folder
          rm -rf "$VERSION"
          cp -r _build/html "$VERSION"
          
          if [[ "$IS_CLEAN" != "1" ]]; then
            touch "$VERSION/.pre-release"
          fi
          
          # Update docs
          ./update.py
          cat versions.json
          
          # Commit and push
          git add "$VERSION" latest versions.json
          git commit -m "Deploy docs/$VERSION"
          git push origin "$PAGES_BRANCH"

  pypi-publish:
    needs: ready
    runs-on: ubuntu-24.04

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}