name: Test

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12', '3.13', '3.14' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --python ${{ matrix.python-version }} --extra full --group examples --group test
      - name: Pytest
        run: |
          uv run --python ${{ matrix.python-version }} \
            pytest tests -v -W error::RuntimeWarning --cov=xplt --cov-report=xml --cov-report=term-missing

  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --group examples --group docs
      - name: Sphinx build
        run: uv run sphinx-build docs _build/html

  prek:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: j178/prek-action@v2
        with:
          extra-args: --all-files
